### ISSUE TITLE
out of memory error when adding many random ip nets

### ISSUE THREAD

**Issue by wxdao** [yl2chen/cidranger#13]
Following code will produce an out of memory fatal error:

```
        trie := cidranger.NewPCTrieRanger()
        rand.Seed(1)
        addr := make([]byte, net.IPv4len)
        for n := 0; n < 1000; n += 1 {
                rand.Read(addr)
                cidr := int(rand.Uint32() % uint32(net.IPv4len*8))
                mask := net.CIDRMask(cidr, net.IPv4len*8)
                trie.Insert(cidranger.NewBasicRangerEntry(net.IPNet{
                        IP:   addr,
                        Mask: mask,
                }))
        }
```

Log shows that it's likely due to too many (*prefixTrie).insert recursive calls.

**Comment by ldkingvivi** [comment]
same thing as I posted in #18 , I don't think you use the legit IPNet, the IP addr are not suppose to be random, but represent the network. You can certainly generate the random string, but use net.ParseCIDR to get the legit IPNet, then see if you will run into issue or not

**Comment by yl2chen** [comment]
Second @ldkingvivi here.

`IPNet` is not to be constructed with the address directly but rather the masted network, https://golang.org/pkg/net/#IPNet

It is also demonstrated by looking at the implementation of `ParseCIDR` https://golang.org/src/net/ip.go?s=16363:16407#L699 where it construct using the masked ip rather than the ip itself, and it is assumed by the implementation of `IPNet`'s functions.
