### ISSUE TITLE
Duplicates are not maintained

### ISSUE THREAD

**Issue by aidansteele** [yl2chen/cidranger#14]
Hi,

I love the library - thanks for sharing it.

I initially assumed that if I inserted duplicate range entries, then both would be returned by `ContainingNetworks()`, but it appears that duplicates are eliminated. Looking at this code, I guess that's intentional? https://github.com/yl2chen/cidranger/blob/928b519e5268fe386d0f7decce320205cc09ca95/trie_test.go#L38-L41

**Comment by yl2chen** [comment]
Yes, deduplication were intentional, the idea behind it is that this will any metadata that you would like to attach to a CIDR block could be done through implementing your own custom type that implements the `RangerEntry` interface https://github.com/yl2chen/cidranger/blob/928b519e5268fe386d0f7decce320205cc09ca95/cidranger.go#L48

Does that fit your use case?

**Comment by aidansteele** [comment]
Thanks for the super speedy response. That's a good point about the interface -- I can do the deduplication _before_ adding the entries and then check a slice in the entry's metadata :)

Thanks for your help!
